controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    mecanum_cont:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link
    front_left_names: ["front_left_joint"]
    front_right_names: ["front_right_joint"]
    back_left_names: ["back_left_joint"]
    back_right_names: ["back_right_joint"]
    wheel_separation_width: 0.31 # Khoang cach giua 2 banh trai/phai
    wheel_separation_length: 0.42 # Khoang cach giua 2 banh truoc/sau
    wheel_radius: 0.1

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    enable_odom_tf: true
    publish_odom: true